### ISSUE TITLE
Support build.dart running when non-source files change

### ISSUE THREAD

**Issue by kevmoo** [kevmoo/source_gen.dart#21]
Like an HTML file – opt in?

**Comment by ferhatb** [comment]
Yes. opt in.

**Comment by kevmoo** [comment]
@ferhatb How would you want to model this?

If we track changes to any file, the generator gets slow.

We could have an option for each generator: SourceFile, SourceLibrary, SameDirectory, SameDirectoryAndChildren, WholeProject

What do you think?

**Comment by ferhatb** [comment]
Option for generator sounds good, i've not seen a case yet where they live
in separate dirs.

**Comment by kevmoo** [comment]
Tiptoeing into this work at branch https://github.com/kevmoo/source_gen.dart/tree/non_source_files_i21

**Comment by kevmoo** [comment]
@ferhatb Look at `JsonLiteralGenerator` for an example. This is published as `0.2.4`. Let me know if you have questions.
