### ISSUE TITLE
json_serializable_generator can't find serializable classes

### ISSUE THREAD

**Issue by luizmineo** [kevmoo/source_gen.dart#35]
I've created the following dart package to test source_gen:

[https://github.com/luizmineo/source_gen_test](https://github.com/luizmineo/source_gen_test)

It contains a `build.dart` script, which is invoked by DartEditor, and the `lib/example_json.dart` library, which has a serializable class. When modifying this file, `lib/example_json.g.dart` should be created, but it seems that source_gen can't find the `Person` class in example_json.dart, and nothing happens.

**Comment by kevmoo** [comment]
Fix published as 0.2.1 - https://pub.dartlang.org/packages/source_gen

Please confirm. Thanks for the report!

**Comment by luizmineo** [comment]
It's working fine now. Thanks!
